import { site } from '../src/config';

const usedIcon: Array<string> = [
    'ri-lg',
    'ri-xl',
    'ri-2x',
    'ri-fw',
    'ri-arrow-go-back-line',
    'ri-arrow-left-s-line',
    'ri-arrow-right-double-fill',
    'ri-arrow-right-line',
    'ri-arrow-right-s-fill',
    'ri-arrow-right-s-line',
    'ri-at-line',
    'ri-book-2-fill',
    'ri-bookmark-fill',
    'ri-bookmark-line',
    'ri-box-3-fill',
    'ri-bubble-chart-fill',
    'ri-building-3-fill',
    'ri-calendar-2-fill',
    'ri-calendar-check-fill',
    'ri-chat-1-line',
    'ri-close-fill',
    'ri-copyright-line',
    'ri-footprint-line',
    'ri-game-fill',
    'ri-gamepad-fill',
    'ri-ghost-smile-fill',
    'ri-git-merge-line',
    'ri-hashtag',
    'ri-mail-fill',
    'ri-menu-3-fill',
    'ri-menu-4-fill',
    'ri-moon-clear-line',
    'ri-pages-line',
    'ri-planet-fill',
    'ri-price-tag-3-line',
    'ri-pushpin-fill',
    'ri-puzzle-fill',
    'ri-qq-fill',
    'ri-question-line',
    'ri-quill-pen-fill',
    'ri-signpost-fill',
    'ri-skip-up-line',
    'ri-stack-fill',
    'ri-sun-line',
    'ri-terminal-box-fill',
];

site.profile.socialLink.map(icon => usedIcon.push(`ri-${icon.iconName}-fill`));

export default usedIcon;
